import type { Metadata } from "next";
import { Inter, Calistoga } from "next/font/google";
import { twMerge } from "tailwind-merge";
import "./globals.css";
import { ConditionalHeader } from "@/components/ConditionalHeader";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
});
const calistoga = Calistoga({
  subsets: ['latin'],
  variable: '--font-serif',
  weight: ['400'],
});

export const metadata: Metadata = {
  title: "Gzaaa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={twMerge(
          inter.variable,
          calistoga.variable,
          "bg-background text-foreground antialiased font-sans"
        )}
      >
        <ConditionalHeader />
        {children}
      </body>
    </html>
  );
}

